### ISSUE TITLE
Is this still maintained? It doesn't really work anymore.

### ISSUE THREAD

**Issue by axefrog** [dabbott/vscode-import-js#12]
As per the other issue, it doesn't successfully write the imports to the editor anymore (stopped working a few weeks ago for me). 

Would love to see this extension working again.

**Comment by trotzig** [comment]
I think @dabbott might be using a different tool/plugin for importing, so I think fixes have to come in from the community. I don’t have much context on this plugin but I’m happy to help review PRs here. I maintain some of the other import-js plugins, plus the main import-js project.

**Comment by dabbott** [comment]
The last 2 PRs were almost the exact opposites of each other 😂. Editor plugins can be kind of tricky. I'll try to find some time to take a look this week. I haven't really been using the plugin anymore so I welcome any PRs @axefrog.

**Comment by axefrog** [comment]
I'd be happy to PR under normal circumstances, it's just that there are probably 10+ things I use that also need PRs, and I'm currently working 60 hours a week, which makes it difficult. Thanks for replying though.
