### ISSUE TITLE
Installation directly from vscode

### ISSUE THREAD

**Issue by trotzig** [dabbott/vscode-import-js#2]
This is more of a question than an issue. I was giving a brief talk on import-js during http://nordicjs.com/ last week. As part of the preparation, I was making animated gifs of import-js in action. In the past, I've only tried running vscode-import-js from source code, not as an installed extension. But this time I thought I'd try installing it the "proper" way through the Extensions UI. However, none of the searches I could come up made vscode-import-js show up in the results. Is there something we have to do in order to fix that?

**Comment by dabbott** [comment]
Hmmm... you're right, the search results don't seem to show it. Per the docs it looks like text search is mainly based on the description and the keywords. https://code.visualstudio.com/docs/extensionAPI/extension-manifest 

Currently if I search "ImportJS" it'll pop up. I bet adding "vscode-import-js" "import-js" "import" and some other variants would help.

**Comment by trotzig** [comment]
Cool, I pushed a PR for this.
