### ISSUE TITLE
Failed to start ImportJS server: spawn importjs ENOENT on Windows 10

### ISSUE THREAD

**Issue by vdumitraskovic** [dabbott/vscode-import-js#4]
I'm not sure what the problem is, but I'm getting 'Failed to start ImportJS server: spawn importjs ENOENT'.

`importjs start` works in console in project dir.

**Comment by trotzig** [comment]
Are you using nodenv/nvm or something similar? It might be that the vscode plugin uses the system node, and you've installed import-js for a different node version.

**Comment by vdumitraskovic** [comment]
@trotzig I'm not using nodenv nor nvm. I'm using node v8.2.1 installed through chocolatey.

**Comment by trotzig** [comment]
This is just a guess, but it's likely that chocolatey sets up some `PATH` related stuff in a startup script (e.g. `.bash_profile`, `.bashrc`, `.zshrc`). That could make `importjs` available in your terminal but not in vscode.

**Comment by vdumitraskovic** [comment]
@dabbott Can you please push the update to the marketplace?

**Comment by dabbott** [comment]
@smesko85 done!
