### ISSUE TITLE
ImportJS encountered an error: undefined

### ISSUE THREAD

**Issue by macrozone** [dabbott/vscode-import-js#8]
i just installed the vscode of import js and tried to import something, but get an error: 

`ImportJS encountered an error: undefined`

**Comment by trotzig** [comment]
Can you try running `importjs` in a terminal outside of vscode? What's the output?

**Comment by macrozone** [comment]
@trotzig i got some parsing errors in the importjs log.

I could fix the problem by removing the `meteor` environment from the importjs file:

```
module.exports = {
  environments: ['node', 'meteor'],
  declarationKeyword: 'import',
  excludes: ['**/tests/**'],
};
```

changed to

```
module.exports = {
  environments: ['node'],
  declarationKeyword: 'import',
  excludes: ['**/tests/**'],
};
```

**Comment by trotzig** [comment]
Interesting. Parsing errors from the meteor config? Would you mind sharing them here, or in a new issue reported upstream to https://github.com/Galooshi/import-js ?

**Comment by macrozone** [comment]
@trotzig 

not much insight though...:

```
1523884547875 ERROR PID:4576 ERROR response: {"error":"Unexpected token (1:15)\nSyntaxError: Unexpected token (1:15)\n    at Parser.pp$5.raise (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:4454:13)\n    at Parser.pp.unexpected (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:1761:8)\n    at Parser.pp$3.parseExprAtom (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:3750:12)\n    at Parser.parseExprAtom (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:7238:22)\n    at Parser.pp$3.parseExprSubscripts (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:3494:19)\n    at Parser.pp$3.parseMaybeUnary (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:3474:19)\n    at Parser.pp$3.parseExprOps (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:3404:19)\n    at Parser.pp$3.parseMaybeConditional (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:3381:19)\n    at Parser.pp$3.parseMaybeAssign (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:3344:19)\n    at Parser.parseMaybeAssign (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:6474:20)"}
```

**Comment by macrozone** [comment]
i managed to get it to work, but it behaves really badly and deletes code ;-(

**Comment by trotzig** [comment]
Yeah that's unfortunate. I know @dabbott might not be using this plugin right now, so perhaps we can figure out a way to get someone else involved in maintaining?

**Comment by macrozone** [comment]
@trotzig yeah, i just switched from atom to vscode, because atom started to annoy me ;-) and i now evalulating vscode.

vscode has some built-in functions for import statements, but it does not do the job as well as importjs does :-/
